// <auto-generated />
using Labb3_API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb3_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220709142806_First init")]
    partial class Firstinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb3_API.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            Description = " the practice of applying paint, pigment, color or other medium to a solid surface",
                            Title = "Painting"
                        },
                        new
                        {
                            HobbyId = 2,
                            Description = "the art, science and craft of using heat to prepare food for consumption",
                            Title = "Cooking"
                        },
                        new
                        {
                            HobbyId = 3,
                            Description = "develop specific motor skills, agility, strength or physical fitness",
                            Title = "Training"
                        },
                        new
                        {
                            HobbyId = 4,
                            Description = " the art of arranging sound",
                            Title = "Music"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            HobbyId = 1,
                            PersonId = 4,
                            URL = "https://en.wikipedia.org/wiki/Painting"
                        },
                        new
                        {
                            LinkId = 2,
                            HobbyId = 2,
                            PersonId = 3,
                            URL = "https://en.wikipedia.org/wiki/Cooking"
                        },
                        new
                        {
                            LinkId = 3,
                            HobbyId = 3,
                            PersonId = 1,
                            URL = "https://en.wikipedia.org/wiki/Training"
                        },
                        new
                        {
                            LinkId = 4,
                            HobbyId = 4,
                            PersonId = 5,
                            URL = "https://en.wikipedia.org/wiki/Music"
                        },
                        new
                        {
                            LinkId = 5,
                            HobbyId = 4,
                            PersonId = 2,
                            URL = "https://www.newworldencyclopedia.org/entry/Music"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Samira",
                            LastName = "Ekberg",
                            PhoneNumber = "0738041775"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Nick",
                            LastName = "Larsson",
                            PhoneNumber = "07226566888"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Ingrid",
                            LastName = "Johansson",
                            PhoneNumber = "0703698366"
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Magnus",
                            LastName = "Lund",
                            PhoneNumber = "0737659489"
                        },
                        new
                        {
                            PersonId = 5,
                            FirstName = "Nelly",
                            LastName = "Stenberg",
                            PhoneNumber = "0718763244"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.PersonHobby", b =>
                {
                    b.Property<int>("PersonHobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonHobbyId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonHobbies");

                    b.HasData(
                        new
                        {
                            PersonHobbyId = 1,
                            HobbyId = 1,
                            PersonId = 4
                        },
                        new
                        {
                            PersonHobbyId = 2,
                            HobbyId = 2,
                            PersonId = 3
                        },
                        new
                        {
                            PersonHobbyId = 3,
                            HobbyId = 3,
                            PersonId = 1
                        },
                        new
                        {
                            PersonHobbyId = 4,
                            HobbyId = 4,
                            PersonId = 5
                        },
                        new
                        {
                            PersonHobbyId = 5,
                            HobbyId = 4,
                            PersonId = 2
                        },
                        new
                        {
                            PersonHobbyId = 6,
                            HobbyId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            PersonHobbyId = 7,
                            HobbyId = 2,
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.Hobby", "Hobby")
                        .WithMany("Links")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb3_API.Models.PersonHobby", b =>
                {
                    b.HasOne("Labb3_API.Models.Hobby", "Hobby")
                        .WithMany("PersonHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.Person", "Person")
                        .WithMany("PersonHobbies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
